name: Build wheels

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build wheels with cibuildwheel

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          pip install "cibuildwheel>=2.13.0"
      
      - name: Build wheels (x86_64, aarch64)
        run: cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: "cp39-* cp310-* cp311-*"
          CIBW_ARCHS_LINUX: "x86_64 aarch64"
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_ARCHS_WINDOWS: "x86_64"
          CIBW_BEFORE_ALL_LINUX: "yum install -y libpcap-devel"
          CIBW_SKIP: "*-musllinux_*"

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: build-wheels
          path: dist/*.whl