name: Build wheels

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Python
        uses: actions/setup-python@v4.8.0
        with:
          python-version: '3.11'
      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          pip install "cibuildwheel>=2.13.0"
      - name: Build wheels (Linux)
        run: cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: "cp39-* cp310-* cp311-*"
          CIBW_ARCHS_LINUX: "x86_64 aarch64"
          CIBW_BEFORE_ALL_LINUX: "apt-get update && apt-get install -y libpcap-dev"
          CIBW_SKIP: "*-musllinux_*"
          CIBW_TEST_COMMAND: "pytest {project}/tests"
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: linux-wheels
          path: dist/*.whl

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up Python
        uses: actions/setup-python@v4.8.0
        with:
          python-version: '3.11'
      - name: Install Rust
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: Add Rust to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Source Rust environment
        run: source $HOME/.cargo/env
        shell: bash
      - name: Add macOS targets for Rust
        run: |
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin
      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          pip install "cibuildwheel>=2.13.0"
      - name: Install dependencies
        run: brew install libpcap
      - name: Build wheels (macOS)
        run: cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: "cp39-* cp310-* cp311-*"
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          MACOSX_DEPLOYMENT_TARGET: "10.12"
          CIBW_TEST_COMMAND: "pytest {project}/tests"
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: macos-wheels
          path: dist/*.whl

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up Python
        uses: actions/setup-python@v4.8.0
        with:
          python-version: '3.11'
      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          pip install "cibuildwheel>=2.13.0"
      - name: Build wheels (Windows)
        run: cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: "cp39-* cp310-* cp311-*"
          CIBW_ARCHS_WINDOWS: "AMD64"
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: windows-wheels
          path: dist/*.whl